### ISSUE TITLE
config.js does not take from SITE_URL

### ISSUE THREAD

**Issue by Bamieh** [PierrePaul/html5-dopetrope#14]
hey buddy, 

First i would like to thank you for the amazing job with the template.

As the name suggests, there is a bug that `skel_configs` do not take from the `SITE_URL` config. to fix this i added the following locally:

```html
<!-- templates/base.html -->
<script>
   window.SITEURL = "{{SITEURL}}"
</script>
```
```js
// static/js/config.js
window._skel_config = {
   ...,
   prefix: `${window.SITEURL}theme/css/style`,
   ...,
}
```
what do you think about this? if we're on the same page i can submit a pull request for you

cheers!

**Comment by PierrePaul** [comment]
Hey, sorry for the long wait. You're totally right. I've made the changes and gave you credit for it :) Thanks!

**Comment by Bamieh** [comment]
thank you!
