### ISSUE TITLE
Please use article.locale_date instead of article.date

### ISSUE THREAD

**Issue by inktrap** [PierrePaul/html5-dopetrope#15]
I would like to customize the date while using this theme. This works with ``article.locale_date`` instead of ``article.date``.

``locale_date | Date formatted by the date_format.`` [Source](http://docs.getpelican.com/en/3.6.3/themes.html#page). As a consequence: Either ``date_format`` is set and ``locale_date`` will give the locale specific output, or the default date format is used anyway.

[See this bugreport which is the same issue for the notmyidea theme](https://github.com/getpelican/pelican/issues/816#issuecomment-15597914)

**Comment by PierrePaul** [comment]
Thanks

**Comment by inktrap** [comment]
Uh and related: Please do not provide a hard-coded format for the date in article.html:

~~~
themes/html5-dopetrope/templates/article.html:									<div class="pennant pennant-alt date">{{ article.date|strftime('%Y-%m-%d') }}</div>
~~~

**Comment by inktrap** [comment]
Btw: your fix is wrong: it is ``page.locale_date`` or ``article.locale_date`` not ``locale_date``.

**Comment by PierrePaul** [comment]
I guess that serves me right for committing and pushing before leaving the office. Thanks. I also made some changes to the styling so it doesnt look too ugly, since Im no longer extracting the date manually.

**Comment by inktrap** [comment]
Meh, we have all done that :) Thanks!
