### ISSUE TITLE
CSS does not load when uploaded to server

### ISSUE THREAD

**Issue by owlas** [PierrePaul/html5-dopetrope#2]
I switched to html5-dopetrope from the pelican-bootstrap3 theme, whilst it looks fantastic in my development server, when I upload it to my web server I simply see my content as plain text, left justified.

It works again by simply changing the line:
    THEME='themes/html5-dopetrope'
to
    THEME='themes/pelican-bootstrap3'

Is it something to do with html5? What has changed between these two versions?

**Comment by PierrePaul** [comment]
Are you sure your SITEURL is set correctly in your publishconf ? There is also the "CDN" variable available (which you can set to SITEURL if you dont want to use it).

**Comment by PierrePaul** [comment]
Closing for now, feel free to re-open if you still have the issue.
