### ISSUE TITLE
Closing div if nr of items in index is not divisible by 3 missing

### ISSUE THREAD

**Issue by neuralyzer** [PierrePaul/html5-dopetrope#4]
Hi,
I think there is a small bug in [line 25 of index.html](https://github.com/PierrePaul/html5-dopetrope/blob/master/templates/index.html#L25). There is no `<\div>` added at the end of the loop if the nr of items is not divisible by 3.

I think the line should be

```
{% if loop.index % 3  == 0 or loop.index == loop.length %}
```

to make sure a closing  `<\div>` is always added at the end of the loop.

**Comment by PierrePaul** [comment]
This seems to have been fixed in 343ceb46788e5ec859a744c862b52ff27742cd87 . Closing. Thanks!
